[tool.poetry]
name = "eql"
version = "0.1"
description = ""
authors = ["CalebJohn <eql@calebjohn.ca>"]

[tool.poetry.dependencies]
python = "^3.7"
sympy = "^1.6.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[project.urls]
Homepage = ""
