[tool.poetry]
name = "eql"
version = "0.1.3"
description = ""
authors = ["CalebJohn <calebjohn4@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
expect = { path = "/home/caleb/code/python/expect/" }

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
