[tool.poetry]
name = "eql"
version = "0.1"
description = ""
authors = ["CalebJohn <calebjohn4@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
sympy = "^1.6.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
pylint = "^2.6.0"
mypy = "^0.790"
black = "^20.8b1"
ipython = "^7.19.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
